# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.TextField(),
        ),
    ]
