# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_add_kind_attribute_to_describe_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
