# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_allow_overriding_created_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
